apiVersion: v1
kind: Service
metadata:
  name: nginx-node
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      name: web
  selector:
    app: nginx-node

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 3000
      name: web
  selector:
    app: backend
